[execution]
mode = "Python"
script = "campaign_censor.py"
hash_seed = 1337

[ethernet]
[ethernet.allowlist]
list = []
[ethernet.blocklist]
list = []

[arp]

[ip]
[ip.allowlist]
list = []
[ip.blocklist]
list = []

[icmp]

[tcp]
[tcp.port_allowlist]
list = []
[tcp.port_blocklist]
list = []
[tcp.ip_port_allowlist]
list = []
[tcp.ip_port_blocklist]
list = []

[udp]
[udp.port_allowlist]
list = []
[udp.port_blocklist]
list = []
[udp.ip_port_allowlist]
list = []
[udp.ip_port_blocklist]
list = []
